# Generated by Django 5.0.6 on 2024-06-25 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.ImageField(default='static/IMG_0024 2.JPG', upload_to='products/'),
        ),
    ]
