# Generated by Django 5.0.6 on 2024-06-25 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_product_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(default='/static/IMG_0024 2.JPG', upload_to='products/'),
        ),
    ]
