# Generated by Django 5.0.6 on 2024-06-26 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_product_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(default='default/IMG_0024 2.JPG', upload_to='products/'),
        ),
    ]
