# Generated by Django 5.0.6 on 2024-06-25 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='admin_type',
            field=models.CharField(choices=[('0', 'bloklangan'), ('1', 'oddiy'), ('2', 'admin qoshish'), ('3', 'mahsulot qoshish')], default='1', max_length=255),
        ),
        migrations.AddField(
            model_name='customuser',
            name='info',
            field=models.TextField(default=''),
        ),
    ]
